http:
  routers:
    backend:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      priority: 100
      middlewares:
        - body-limit
      service: backend

    # дизайн решение @pxc1984: будем тихо дропать такие запросы вместо проверки секрета. вторая защита получается
    backend-bot-to-frontend:
      rule: "PathPrefix(`/api/bot`)"
      entryPoints:
        - web
      priority: 200
      service: frontend

    frontend:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      priority: 1
      service: frontend

  middlewares:
    body-limit:
      buffering:
        maxRequestBodyBytes: 15728640

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
